apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kubia
spec:
  replicas: 3
  # Used to prevent deploying malfunctioning versions
  # specifies how long a newly created pod should be ready before the pod is treated as available.
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      # These 2 properties affect how many pods are replaced at once during the deployments rolling update.
      # maxSurge - determines how many pod instances you allow to exist above the desired replica count configured on the Deployment. It
      maxSurge: 1
      # Determines how many pod instances can be unavailable relative to the desired replica count during the update.
      # in other words, (replicas #) had to be available at all times.
      # set to 0 to make pods replace one by one.
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
      - image: luksa/kubia:v3
        name: nodejs
        resources:
          limits:
            cpu: 250m
            memory: 64Mi
          requests:
            cpu: 250m
            memory: 64Mi
        readinessProbe:
          # readiness probe will be executed every second.
          periodSeconds: 1
          httpGet:
            path: /
            port: 8080
