apiVersion: v1
kind: Pod
metadata:
  name: curl
spec:
  containers:
  - name: main
    # using the tatum/curl image, bc you need curl available inside the container
    image: curlimages/curl
    # runninn sleep command with long delay to keep the container running
    command: ["sleep", "9999999"]
