apiVersion: v1
kind: Service
metadata:
  name: {{ include "istio-demo.fullname" . }}
  labels:
    {{- include "istio-demo.labels" . | nindent 4 }}
    # app: flaskapp
    # service: flaskapp
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    {{- include "istio-demo.selectorLabels" . | nindent 4 }}
    # app: flaskapp
