apiVersion: v1
kind: Pod
metadata:
  name: fortune-configmap-volume-with-certain-items
  labels:
    app: fortune
spec:
  containers:
  - image: luksa/fortune:env
    name: html-generator
    resources:
      requests:
        cpu: "100m"
        memory: "512M"
      limits:
        cpu: "1000m"
        memory: "512M"
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  - image: nginx:alpine
    name: web-server
    resources:
      requests:
        cpu: "100m"
        memory: "512M"
      limits:
        cpu: "1000m"
        memory: "512M"
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    - name: config
      # mounting into a file, not a directory.
      mountPath: /etc/nginx/conf.d/
      # Instead of mounting the whole volume, you're only mounting the my config.conf entry.
      subPath: myconfig.conf
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    emptyDir: {}
  - name: config
    configMap:
      name: fortune-config
      items:
        # Selecting which entries to include in the volume by listing them.
      - key: my-nginx-config.conf
        path: gzip.conf
