apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: podinfo-ingress
  namespace: test
spec:
  virtualhost:
    fqdn: pod-info-example.gcp.development.website.com
    tls:
      secretName: platform/prod-wildcard-gcp-development-website-com-tls
  includes:
    - name: podinfo
      namespace: test
      conditions:
        - prefix: /
