apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress-resource
  annotations:
    #app.kubernetes.io/component: ingress
    # app: demo
    # enabled: "true"
    # If you're running multiple ingress controllers, or running on a cloud provider that natively handles ingress such as GKE,
    # you need to specify the annotation kubernetes.io/ingress.class: "nginx" in all ingresses that you would like the ingress-nginx controller to claim.
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    # This ingress maps the demo.example.com domain name to your service
    - host: demo.example.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            # All requests will be sent to port 80 of the demo-nodeport service
            backend:
              service:
                name: demo-nodeport
                port:
                  number: 80
                  # servicePort: 8080
          - path: "/fortune"
            pathType: Prefix
            # All requests will be sent to port 80 of the demo-loadbalancer service
            backend:
              service:
                name: demo-loadbalancer
                port:
                  number: 3200
    # any web traffic to the IP address of your Ingress controller can be matched without a name based virtual host being required.
    # For example, the following Ingress routes traffic requested for demo.example.com to nodePort or LB,
    # and any traffic to the IP address without a hostname defined in request (that is, without a request header being presented) to service defined below.
    # - http:
    #     paths:
    #       - pathType: Prefix
    #         path: "/"
    #         # All requests will be sent to port 80 of the demo-loadbalancer service
    #         backend:
    #           service:
    #             name: demo-loadbalancer
    #             port:
    #               number: 3200
