# File describes a list of three PV's
kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    # The PVs' names are pv-a, pv-b, and pv-c
    name: pv-a
  spec:
    # The capacity of each PV is 1 Mebibyte
    capacity:
      storage: 1Mi
    accessModes:
      - ReadWriteOnce
    # When the volume is released by the claim, it's recycled to be used again
    persistentVolumeReclaimPolicy: Recycle
    # The volume uses a GCE Persistent Disk as the underlying storage mechanism
    gcePersistentDisk:
      pdName: pv-a
      fsType: ext4
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv-b
  spec:
    capacity:
      storage: 1Mi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    gcePersistentDisk:
      pdName: pv-b
      fsType: ext4
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv-c
  spec:
    capacity:
      storage: 1Mi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    gcePersistentDisk:
      pdName: pv-c
      fsType: ext4
