apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: stateful-pod-peers
spec:
  # The headless service that will act as the governing service for the statefulset pod
  serviceName: governing-service
  replicas: 3
  selector:
    matchLabels:
      app: stateful # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: stateful
    spec:
      # the StatefulSet controller will delete and recreate each Pod in the StatefulSet.
      # It will proceed in the same order as Pod termination (from the largest ordinal to the smallest), updating each Pod one at a time.
      updateStrategy:
        type: RollingUpdate
      terminationGracePeriodSeconds: 10
      containers:
      - name: kubia
        image: luksa/kubia-pet-peers
        ports:
        - name: http
          containerPort: 8080
        # The container inside the pod will mount the PVC volume at this path
        volumeMounts:
        - name: data
          mountPath: /var/data
  # The PVCs will be created from this template
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      resources:
        requests:
          storage: 1Mi
      accessModes:
      - ReadWriteOnce
