apiVersion: v1
kind: Pod
metadata:
  name: curl-with-ambassador
spec:
  containers:
  - name: main
    image: curlimages/curl
    command: ["sleep", "9999999"]
    # the ambassador container running the kubectl-proxy image
  - name: ambassador
    image: luksa/kubectl-proxy:1.6.2


# Exec into this pod and into the main container, and hit the api server using the ambassador container as a proxy
# to skip all the manual authentication steps and dealing with CA certs and tokens. Use kubectl proxy to your advantage.
# kubectl exec -it curl-with-ambassador -c main -- sh
# or
# kubectl exec -it curl-with-ambassador -c main bash
# because both containers in the podshare the same network interfaces, including loopback, you can point curl to localhost:8001
# curl localhost:8001
