apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-app-api.fullname" . }}-service
  labels:
    {{- include "flask-app-api.labels" . | nindent 4 }}
spec:
  selector:
    app: flask-app
    {{- include "flask-app-api.selectorLabels" . | nindent 4 }}
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
