{{- if .Values.https.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: https
type: Opaque
data:
  # Turn into base 64 encoded with echo -n 'example' | base64
  https.key: |
      # private key here
{{- end }}
