{{- if .Values.loadbalancer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-app-api.fullname" . }}-lb
  labels:
    {{- include "flask-app-api.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
    - name: https
      port: 443
      targetPort: 5000
      protocol: TCP
  selector:
    app: flask-app
    {{- include "flask-app-api.selectorLabels" . | nindent 4 }}
{{- end }}
