{{- $port := .Values.service.port -}}
{{- $targetPort := .Values.service.targetPort -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-app-api.fullname" . }}
  labels:
    {{- include "flask-app-api.labels" . | nindent 4 }}
spec:
  selector:
    app: flask-app
    {{- include "flask-app-api.selectorLabels" . | nindent 4 }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  type: LoadBalancer
  externalTrafficPolicy: Local
  {{- else if eq .Values.service.type "NodePort" }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
  - port: {{ $port }}
    targetPort: {{ $targetPort }}
    protocol: TCP
