{{- if .Values.https.tls.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
{{- range .Values.ingress.tls }}
  name: {{ .secretName }}
{{- end }}
type: Opaque
data:
  tls.key: |
    # base64 encoded key
  tls.cert: |
    # base64 encoded cert
{{- end }}
